import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthWrapper } from "../utils/AuthContext";
import ProtectedRoute from "@/utils/ProtectedRoute";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthWrapper>{children}</AuthWrapper>
      </body>
    </html>
  );
}
// model Porjects {

// }

// projetcts/add/id  >> listing of all projects
// add new project button
// new page > project name, desc, // db status is live,draft 